404 page
3h-hareketi/akademi pull request #51
Opened 2022-03-19 15:31 UTC by berkedozden

2022-03-19 15:34 UTC, thiras requested changes

2022-03-19 15:34 UTC, thiras commented on pages/404.tsx
> +        <div className="grid justify-items-center">
mumkun olan her zaman flew over grid

2022-03-19 15:34 UTC, thiras commented on pages/404.tsx
> +          <Image
placeholder eksik https://nextjs.org/docs/api-reference/next/image#placeholder

2022-03-19 23:34 UTC, berkedozden reviewed
https://nextjs.org/docs/messages/placeholder-blur-data-url

2022-03-20 18:56 UTC, thiras approved these changes

2022-03-20 18:58 UTC, merged